runtime: go
api_version: go1

handlers:
- url: /
  static_files: site/index.html
  upload: site/index.html

- url: /(.*)/
  static_files: site/\1/index.html
  upload: .*/index\.html

- url: /
  static_dir: site
